import { BossDefinition, BossId } from './types';

export const BOSS_DEFINITIONS: BossDefinition[] = [
  {
    id: 'shukaku',
    number: 1,
    name: 'Shukaku',
    village: 'Hidden Sand Village',
    attacks: ['Sand Burial Spiral', 'Desert Spear Field'],
    reward: 'Sand Armor Powerup',
    color: '#c48a4a',
    tails: 1,
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'matatabi',
    number: 2,
    name: 'Matatabi',
    village: 'Hidden Cloud Outskirts',
    attacks: ['Blue Flame Rush', 'Twin-Tail Fire Burst'],
    reward: 'Fire Bomb Upgrade',
    color: '#2563eb',
    tails: 2,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'isobu',
    number: 3,
    name: 'Isobu',
    village: 'Mist Village',
    attacks: ['Coral Water Cannon', 'Shell Tide Pools'],
    reward: 'Water Walk Ability',
    color: '#0e7490',
    tails: 3,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'sonGoku',
    number: 4,
    name: 'Son Goku',
    village: 'Volcano Map',
    attacks: ['Lava Fist Eruption', 'Magma Field'],
    reward: 'Explosion Immunity',
    color: '#dc2626',
    tails: 4,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'kokuo',
    number: 5,
    name: 'Kokuo',
    village: 'Steam Valley',
    attacks: ['Boil Release Charge', 'Steam Horn Burst'],
    reward: 'Speed Boost',
    color: '#e5e7eb',
    tails: 5,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'saiken',
    number: 6,
    name: 'Saiken',
    village: 'Swamp Village',
    attacks: ['Acid Bubble Field', 'Corrosive Mist Spit'],
    reward: 'Poison Immunity',
    color: '#7c3aed',
    tails: 6,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'chomei',
    number: 7,
    name: 'Chomei',
    village: 'Forest Village',
    attacks: ['Wing Scale Barrage', 'Sky Drop Strike'],
    reward: 'Temporary Flight',
    color: '#16a34a',
    tails: 7,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'gyuki',
    number: 8,
    name: 'Gyuki',
    village: 'Cloud Village',
    attacks: ['Octo-Lariat Slam', 'Tailed Beast Bomb'],
    reward: 'Extra Health',
    color: '#7c2d12',
    tails: 8,
    assetSlots: {},
    implemented: false,
  },
  {
    id: 'kurama',
    number: 9,
    name: 'Kurama',
    village: 'Hidden Leaf at Night',
    attacks: ['Tailed Beast Bomb', 'Nine-Tails Shockwave'],
    reward: 'Sage Naruto Unlock',
    color: '#f97316',
    tails: 9,
    assetSlots: {},
    implemented: false,
  },
];

export function getBossDefinition(id?: BossId | string): BossDefinition {
  return BOSS_DEFINITIONS.find((boss) => boss.id === id) ?? BOSS_DEFINITIONS[0];
}
