import { PowerupDefinition } from './types';

export const POWERUP_DEFINITIONS: PowerupDefinition[] = [
  {
    id: 'chakraCapacity',
    name: 'Character Bomb Training',
    effect: 'Extra bomb or seal capacity',
    color: '#f97316',
    assetSlots: {},
  },
  {
    id: 'chakraAmplification',
    name: 'Blast Mastery',
    effect: 'Wider character-specific explosion',
    color: '#22c55e',
    assetSlots: {},
  },
  {
    id: 'bodyFlicker',
    name: 'Movement Technique',
    effect: 'Speed boost',
    color: '#60a5fa',
    assetSlots: {},
  },
  {
    id: 'earthTunneling',
    name: 'Barrier Technique',
    effect: 'Placeable cover tools',
    color: '#a16207',
    assetSlots: {},
  },
  {
    id: 'windPush',
    name: 'Phase Technique',
    effect: 'Phase-style survival tool',
    color: '#16a34a',
    assetSlots: {},
  },
  {
    id: 'clayDetonation',
    name: 'Detonation Tag',
    effect: 'Remote trigger',
    color: '#dc2626',
    assetSlots: {},
  },
  {
    id: 'susanooFragment',
    name: 'Susanoo Fragment',
    effect: 'Temporary shield',
    color: '#7c3aed',
    assetSlots: {},
  },
  {
    id: 'claySpider',
    name: 'Clay Spider',
    effect: 'Deidara campaign pickup: extra bomb capacity and blast reach',
    color: '#f97316',
    assetSlots: {},
  },
  {
    id: 'rasengan',
    name: 'Rasengan',
    effect: 'Naruto campaign pickup: blast reach and ultimate charge',
    color: '#38bdf8',
    assetSlots: {},
  },
  {
    id: 'sharingan',
    name: 'Sharingan',
    effect: 'Uchiha campaign pickup: manual timing and ultimate charge',
    color: '#ef4444',
    assetSlots: {},
  },
  {
    id: 'ftgKunai',
    name: 'FTG Kunai',
    effect: 'Minato campaign pickup: Yellow Flash speed and ultimate charge',
    color: '#facc15',
    assetSlots: {},
  },
  {
    id: 'crowFeather',
    name: 'Crow Feather',
    effect: 'Itachi campaign pickup: temporary phase dodge',
    color: '#111827',
    assetSlots: {},
  },
  {
    id: 'sandArmor',
    name: 'Sand Armor',
    effect: 'Gaara campaign pickup: temporary shield',
    color: '#c48a4a',
    assetSlots: {},
  },
  {
    id: 'characterFragment',
    name: 'Character Fragment',
    effect: 'Rare campaign reward from hidden areas and elite Zetsu outcomes',
    color: '#a855f7',
    assetSlots: {},
  },
];
