import { StageDefinition, StageId } from './types';

export const STAGE_DEFINITIONS: StageDefinition[] = [
  {
    id: 'hiddenLeaf',
    name: 'Hidden Leaf Village',
    mapId: 'hiddenLeaf',
    theme: 'Forest village lanes with timber walls, trap leaves, and monument colors.',
    mechanic: 'Leaf traps pulse in cross patterns before bursting.',
    bossId: 'kurama',
    palette: {
      groundA: '#b6d6b9',
      groundB: '#a4c9b0',
      wall: '#698d83',
      crate: '#d78f76',
      accent: '#ff8a00',
    },
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'hiddenSand',
    name: 'Hidden Sand Village',
    mapId: 'hiddenSand',
    theme: 'Desert arena with carved stone alleys and drifting sand cover.',
    mechanic: 'Sand tornadoes chase players and force lane changes.',
    bossId: 'shukaku',
    palette: {
      groundA: '#ebcba4',
      groundB: '#dfba8f',
      wall: '#b57f83',
      crate: '#df916e',
      accent: '#facc15',
    },
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'hiddenMist',
    name: 'Hidden Mist Village',
    mapId: 'hiddenMist',
    theme: 'Wet stone bridges with low fog and water-channel chokepoints.',
    mechanic: 'Water cannons fire long telegraphed lines.',
    bossId: 'isobu',
    palette: {
      groundA: '#a8cdd0',
      groundB: '#91bfc5',
      wall: '#668d9f',
      crate: '#d49ba7',
      accent: '#7dd3fc',
    },
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'hiddenCloud',
    name: 'Hidden Cloud Village',
    mapId: 'hiddenCloud',
    theme: 'Sky platforms, storm lanes, and broken cloud cover.',
    mechanic: 'Tentacle slams and lightning lanes split the arena.',
    bossId: 'gyuki',
    palette: {
      groundA: '#b8cfda',
      groundB: '#a5c0d0',
      wall: '#778cae',
      crate: '#e2ae88',
      accent: '#60a5fa',
    },
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'hiddenStone',
    name: 'Hidden Stone Village',
    mapId: 'hiddenStone',
    theme: 'Canyon walls and boulder corridors with heavy cover.',
    mechanic: 'Steam charges shove players out of safe routes.',
    bossId: 'kokuo',
    palette: {
      groundA: '#c6c9ad',
      groundB: '#b5bea1',
      wall: '#888f83',
      crate: '#ca9b79',
      accent: '#e5e7eb',
    },
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'akatsukiHideout',
    name: 'Akatsuki Hideout',
    mapId: 'akatsukiHideout',
    theme: 'Dark ritual cave with red seal markings and ambush corridors.',
    mechanic: 'Blue fire trails and seal bursts punish predictable movement.',
    bossId: 'matatabi',
    palette: {
      groundA: '#b9a4bb',
      groundB: '#a992af',
      wall: '#775e7d',
      crate: '#c77e88',
      accent: '#dc2626',
    },
    assetSlots: {},
    implemented: true,
  },
  {
    id: 'greatShinobiWar',
    name: 'Great Shinobi War',
    mapId: 'greatShinobiWar',
    theme: 'Final battlefield lanes with broken cover, war banners, and chakra-scarred ground.',
    mechanic: 'Kurama shockwaves and beast bombs punish players who stay grouped too long.',
    bossId: 'kurama',
    palette: {
      groundA: '#b5b4c1',
      groundB: '#a4a5b7',
      wall: '#687385',
      crate: '#ce7c78',
      accent: '#fb923c',
    },
    assetSlots: {},
    implemented: true,
  },
];

export const DEFAULT_STAGE_ID: StageId = 'hiddenLeaf';

export function getStageDefinition(id?: string): StageDefinition {
  return STAGE_DEFINITIONS.find((stage) => stage.id === id) ?? STAGE_DEFINITIONS[0];
}
